spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PersonalityTestDB
    username: root
    password: 564955
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true